apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecos
  labels:
    app: ecos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecos
  template:
    metadata:
      labels:
        app: ecos
    spec:
      containers:
        - name: ecos
          image: nkzren/ecos
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: ecos-config
            items:
              - key: "config.yaml"
                path: "config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: ecos-service
spec:
  selector:
    app: ecos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
