apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoscheduler
  labels:
    app: ecoscheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecoscheduler
  template:
    metadata:
      labels:
        app: ecoscheduler
    spec:
      containers:
        - name: ecoscheduler
          image: nkzren/ecoscheduler
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: ecoscheduler-config
            items:
              - key: "config.yaml"
                path: "config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: ecoscheduler-service
spec:
  selector:
    app: ecoscheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
