apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecos
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update"]
- apiGroups: ["apps"]
  resources: ["deployment"]
  verbs: ["get", "watch", "list", "update"]
